"""initial schema

Revision ID: 2fe655bff3db
Revises:
Create Date: 2026-10-05 13:25:10.633604
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (autogenerate writes sqlmodel column types)
from alembic import op

revision: str = "2fe655bff3db"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gametype",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scoring", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("roles", sa.JSON(), nullable=False),
        sa.Column("points_to_win", sa.Integer(), nullable=True),
        sa.Column("allow_draws", sa.Boolean(), nullable=False),
        sa.Column("team_strength", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("beta", sa.Float(), nullable=False),
        sa.Column("default_sigma", sa.Float(), nullable=False),
        sa.Column("role_correlation", sa.Float(), nullable=False),
        sa.Column("skill_scale", sa.Float(), nullable=False),
        sa.Column("tau", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("session_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_type_id", sa.Integer(), nullable=False),
        sa.Column("played_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("score_a", sa.Integer(), nullable=False),
        sa.Column("score_b", sa.Integer(), nullable=False),
        sa.Column("outcome", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["game_type_id"],
            ["gametype.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("game", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_game_game_type_id"), ["game_type_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_game_played_at"), ["played_at"], unique=False)

    op.create_table(
        "invite",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("expires_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("used_by", sa.Integer(), nullable=True),
        sa.Column("used_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["used_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "player",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "gameparticipant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("side", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mu_before", sa.JSON(), nullable=True),
        sa.Column("cov_before", sa.JSON(), nullable=True),
        sa.Column("mu_after", sa.JSON(), nullable=True),
        sa.Column("cov_after", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("gameparticipant", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_gameparticipant_game_id"), ["game_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_gameparticipant_player_id"), ["player_id"], unique=False
        )

    op.create_table(
        "playerrating",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("game_type_id", sa.Integer(), nullable=False),
        sa.Column("prior", sa.JSON(), nullable=False),
        sa.Column("mu", sa.JSON(), nullable=False),
        sa.Column("cov", sa.JSON(), nullable=False),
        sa.Column("games_played", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("draws", sa.Integer(), nullable=False),
        sa.Column("last_played_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_type_id"],
            ["gametype.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "game_type_id"),
    )
    with op.batch_alter_table("playerrating", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_playerrating_game_type_id"), ["game_type_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_playerrating_player_id"), ["player_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("playerrating", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_playerrating_player_id"))
        batch_op.drop_index(batch_op.f("ix_playerrating_game_type_id"))

    op.drop_table("playerrating")
    with op.batch_alter_table("gameparticipant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gameparticipant_player_id"))
        batch_op.drop_index(batch_op.f("ix_gameparticipant_game_id"))

    op.drop_table("gameparticipant")
    op.drop_table("player")
    op.drop_table("invite")
    with op.batch_alter_table("game", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_game_played_at"))
        batch_op.drop_index(batch_op.f("ix_game_game_type_id"))

    op.drop_table("game")
    op.drop_table("users")
    op.drop_table("gametype")
    # ### end Alembic commands ###
